### ISSUE TITLE
Feature request: ADB Permission

### ISSUE THREAD

**Issue by DeanWinchesterrr** [libxzr/FivegTile#3]
Hi Greetings

Is it possible to add ADB Permission such as

adb shell pm grant pkg.name android.permission.WRITE_SECURE_SETTINGS.

In order to achieve the same without the need for root access

**Comment by libxzr** [comment]
That's not possible because it requires `MODIFY_PHONE_STATE`, which is a system permission and can not be granted to user apps.

https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-14.0.0_r45/telephony/java/android/telephony/TelephonyManager.java#9570

**Comment by 5ham5h33r** [comment]
@libxzr If I set the app to a system app using adb from custom recovery, can I bypass the root restrictions?
